### ISSUE TITLE
スキル間のポイントの融通

### ISSUE THREAD

**Issue by cpro** [cpro/dq10skill#11]
http://twitter.com/xenate/status/430147875230601216
>やっぱり、同じ項目に色つけれないかな～～というのも、
>スキルの融通をする場合に、盾と爆裂と対象スキル１つか２つで調整しないといけない場合があって、
>リンクしてローテーションで操作できればいいんだけど、
>それやるの難しいですよね？？
>できるんなら、やってほしいけど。

http://twitter.com/xenate/status/430150407105437697
>あと共通スキルの１００以上の割り当てが出来るようにしてもらってもいいかもしれません。
>
>そうしてもらうと、調整しやすくなると思います。
>
>ワンボタンで「残りに移動」あっても便利かもｗ

**Comment by cpro** [comment]
スキルライン間でリンクする機能がだいぶ前に頓挫し、それっきり放置状態でした。ごめんなさい。
たいへんお待たせしてしまいましたが、v7.0 b942b0f で、（もう150Pになっちゃいましたが）最大値を超えてスキルポイントを振れるように変更しました。

**Comment by blueberrystream** [comment]
:+1: :+1: :+1:
